// <auto-generated />
using System;
using Common.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Common.Data.Migrations
{
    [DbContext(typeof(QLNVDbContext))]
    [Migration("20210601081459_SuaLaiLienKetChiTietHopDongVaHopDong")]
    partial class SuaLaiLienKetChiTietHopDongVaHopDong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Data.Model.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRole");
                });

            modelBuilder.Entity("Common.Data.Model.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Common.Data.Model.BacLuong", b =>
                {
                    b.Property<int>("MaBacLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .HasColumnType("int");

                    b.Property<string>("LoaiLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucLuong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("MaBacLuong");

                    b.ToTable("BacLuong");
                });

            modelBuilder.Entity("Common.Data.Model.BangCap", b =>
                {
                    b.Property<int>("MaBangCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HeDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaHSNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("NoiDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBangCap");

                    b.HasIndex("MaHSNV");

                    b.ToTable("BangCap");
                });

            modelBuilder.Entity("Common.Data.Model.ChiTietHopDong", b =>
                {
                    b.Property<int>("MaCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<int?>("MaQL")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("MaCTHD");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaNV")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.HasIndex("MaQL");

                    b.ToTable("ChiTietHopDong");
                });

            modelBuilder.Entity("Common.Data.Model.ChiTietKhoaDaoTao", b =>
                {
                    b.Property<int>("MaHV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaKhoaDaoTao")
                        .HasColumnType("int");

                    b.Property<string>("TenHocVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Truong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHV");

                    b.HasIndex("MaKhoaDaoTao");

                    b.ToTable("ChiTietKhoaDaoTao");
                });

            modelBuilder.Entity("Common.Data.Model.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("Common.Data.Model.ChucVuNhanVien", b =>
                {
                    b.Property<int>("MaCVNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBoNhiem")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCVNV");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaNV")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.ToTable("ChucVuNhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.CongTy", b =>
                {
                    b.Property<int>("MaCongTy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCongTy");

                    b.ToTable("CongTy");
                });

            modelBuilder.Entity("Common.Data.Model.DonXin", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<string>("LoaiDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayViet")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("0");

                    b.HasKey("MaDon");

                    b.HasIndex("MaNV");

                    b.ToTable("DonXin");
                });

            modelBuilder.Entity("Common.Data.Model.HoSoNhanVien", b =>
                {
                    b.Property<int>("MaHSNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruongHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHSNV");

                    b.ToTable("HoSoNhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHopDong");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("Common.Data.Model.KhoaDaoTao", b =>
                {
                    b.Property<int>("MaKhoaDaoTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoaDaoTao");

                    b.HasIndex("MaNV");

                    b.ToTable("KhoaDaoTao");
                });

            modelBuilder.Entity("Common.Data.Model.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaBacLuong")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhuCap")
                        .HasColumnType("int");

                    b.Property<int?>("MaThuong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Thang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("luong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaLuong");

                    b.HasIndex("MaBacLuong");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPhuCap");

                    b.HasIndex("MaThuong");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("Common.Data.Model.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CongTyMaCongTy")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<int?>("MaHSNV")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("CongTyMaCongTy");

                    b.HasIndex("MaHSNV")
                        .IsUnique()
                        .HasFilter("[MaHSNV] IS NOT NULL");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongBan");

                    b.HasIndex("MaCongTy");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("Common.Data.Model.PhuCap", b =>
                {
                    b.Property<int>("MaPhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<string>("LoaiPhuCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MucPhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("MaPhuCap");

                    b.ToTable("PhuCap");
                });

            modelBuilder.Entity("Common.Data.Model.QuanLy", b =>
                {
                    b.Property<int>("MaQL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CongTyMaCongTy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<double?>("NamKinhNghiem")
                        .HasColumnType("float");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int?>("Quyen")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQL");

                    b.HasIndex("CongTyMaCongTy");

                    b.ToTable("QuanLy");
                });

            modelBuilder.Entity("Common.Data.Model.QuyetDinhBoNhiem", b =>
                {
                    b.Property<int>("MaQDBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<int?>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<int?>("MaQL")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBoNhiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("MaQDBN");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaQL");

                    b.ToTable("QuyetDinhBoNhiem");
                });

            modelBuilder.Entity("Common.Data.Model.Thuong", b =>
                {
                    b.Property<int>("MaThuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsHide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("1");

                    b.Property<string>("LoaiThuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MucThuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("MaThuong");

                    b.ToTable("Thuong");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("Common.Data.Model.BangCap", b =>
                {
                    b.HasOne("Common.Data.Model.HoSoNhanVien", "HoSoNhanVien")
                        .WithMany("BangCaps")
                        .HasForeignKey("MaHSNV");

                    b.Navigation("HoSoNhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.ChiTietHopDong", b =>
                {
                    b.HasOne("Common.Data.Model.HopDong", "HopDong")
                        .WithMany("ChiTietHopDongs")
                        .HasForeignKey("MaHopDong");

                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithOne("ChiTietHopDong")
                        .HasForeignKey("Common.Data.Model.ChiTietHopDong", "MaNV");

                    b.HasOne("Common.Data.Model.QuanLy", "QuanLy")
                        .WithMany("ChiTietHopDongs")
                        .HasForeignKey("MaQL");

                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");

                    b.Navigation("QuanLy");
                });

            modelBuilder.Entity("Common.Data.Model.ChiTietKhoaDaoTao", b =>
                {
                    b.HasOne("Common.Data.Model.KhoaDaoTao", "KhoaDaoTao")
                        .WithMany("ChiTietKhoaDaoTaos")
                        .HasForeignKey("MaKhoaDaoTao");

                    b.Navigation("KhoaDaoTao");
                });

            modelBuilder.Entity("Common.Data.Model.ChucVuNhanVien", b =>
                {
                    b.HasOne("Common.Data.Model.ChucVu", "ChucVu")
                        .WithMany("ChucVuNhanVien")
                        .HasForeignKey("MaChucVu");

                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithOne("ChucVuNhanVien")
                        .HasForeignKey("Common.Data.Model.ChucVuNhanVien", "MaNV");

                    b.Navigation("ChucVu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.DonXin", b =>
                {
                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithMany("DonXins")
                        .HasForeignKey("MaNV");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.KhoaDaoTao", b =>
                {
                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithMany("KhoaDaoTaos")
                        .HasForeignKey("MaNV");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.Luong", b =>
                {
                    b.HasOne("Common.Data.Model.BacLuong", "BacLuong")
                        .WithMany("Luongs")
                        .HasForeignKey("MaBacLuong");

                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithMany("Luong")
                        .HasForeignKey("MaNV");

                    b.HasOne("Common.Data.Model.PhuCap", "PhuCap")
                        .WithMany("Luongs")
                        .HasForeignKey("MaPhuCap");

                    b.HasOne("Common.Data.Model.Thuong", "Thuong")
                        .WithMany("Luongs")
                        .HasForeignKey("MaThuong");

                    b.Navigation("BacLuong");

                    b.Navigation("NhanVien");

                    b.Navigation("PhuCap");

                    b.Navigation("Thuong");
                });

            modelBuilder.Entity("Common.Data.Model.NhanVien", b =>
                {
                    b.HasOne("Common.Data.Model.CongTy", "CongTy")
                        .WithMany("NhanViens")
                        .HasForeignKey("CongTyMaCongTy");

                    b.HasOne("Common.Data.Model.HoSoNhanVien", "HoSoNhanVien")
                        .WithOne("NhanVien")
                        .HasForeignKey("Common.Data.Model.NhanVien", "MaHSNV");

                    b.HasOne("Common.Data.Model.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan");

                    b.Navigation("CongTy");

                    b.Navigation("HoSoNhanVien");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Common.Data.Model.PhongBan", b =>
                {
                    b.HasOne("Common.Data.Model.CongTy", "CongTy")
                        .WithMany("PhongBans")
                        .HasForeignKey("MaCongTy");

                    b.Navigation("CongTy");
                });

            modelBuilder.Entity("Common.Data.Model.QuanLy", b =>
                {
                    b.HasOne("Common.Data.Model.CongTy", "CongTy")
                        .WithMany("QuanLies")
                        .HasForeignKey("CongTyMaCongTy");

                    b.Navigation("CongTy");
                });

            modelBuilder.Entity("Common.Data.Model.QuyetDinhBoNhiem", b =>
                {
                    b.HasOne("Common.Data.Model.ChucVu", "ChucVu")
                        .WithMany("QuyetDinhBoNhiems")
                        .HasForeignKey("MaChucVu");

                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithMany("QuyetDinhBoNhiems")
                        .HasForeignKey("MaNV");

                    b.HasOne("Common.Data.Model.QuanLy", "QuanLy")
                        .WithMany("QuyetDinhBoNhiems")
                        .HasForeignKey("MaQL");

                    b.Navigation("ChucVu");

                    b.Navigation("NhanVien");

                    b.Navigation("QuanLy");
                });

            modelBuilder.Entity("Common.Data.Model.BacLuong", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("Common.Data.Model.ChucVu", b =>
                {
                    b.Navigation("ChucVuNhanVien");

                    b.Navigation("QuyetDinhBoNhiems");
                });

            modelBuilder.Entity("Common.Data.Model.CongTy", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("PhongBans");

                    b.Navigation("QuanLies");
                });

            modelBuilder.Entity("Common.Data.Model.HoSoNhanVien", b =>
                {
                    b.Navigation("BangCaps");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.HopDong", b =>
                {
                    b.Navigation("ChiTietHopDongs");
                });

            modelBuilder.Entity("Common.Data.Model.KhoaDaoTao", b =>
                {
                    b.Navigation("ChiTietKhoaDaoTaos");
                });

            modelBuilder.Entity("Common.Data.Model.NhanVien", b =>
                {
                    b.Navigation("ChiTietHopDong");

                    b.Navigation("ChucVuNhanVien");

                    b.Navigation("DonXins");

                    b.Navigation("KhoaDaoTaos");

                    b.Navigation("Luong");

                    b.Navigation("QuyetDinhBoNhiems");
                });

            modelBuilder.Entity("Common.Data.Model.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Common.Data.Model.PhuCap", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("Common.Data.Model.QuanLy", b =>
                {
                    b.Navigation("ChiTietHopDongs");

                    b.Navigation("QuyetDinhBoNhiems");
                });

            modelBuilder.Entity("Common.Data.Model.Thuong", b =>
                {
                    b.Navigation("Luongs");
                });
#pragma warning restore 612, 618
        }
    }
}
