// <auto-generated />
using System;
using Common.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Common.Data.Migrations
{
    [DbContext(typeof(QLNVDbContext))]
    [Migration("20210519151944_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Data.Model.BacLuong", b =>
                {
                    b.Property<int>("MaBacLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoaiLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucLuong")
                        .HasColumnType("int");

                    b.HasKey("MaBacLuong");

                    b.ToTable("BacLuong");
                });

            modelBuilder.Entity("Common.Data.Model.BangCap", b =>
                {
                    b.Property<int>("MaBangCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HeDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<string>("NoiDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBangCap");

                    b.HasIndex("MaNV");

                    b.ToTable("BangCap");
                });

            modelBuilder.Entity("Common.Data.Model.ChiTietHopDong", b =>
                {
                    b.Property<int>("MaCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHopDong")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaQL")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("MaCTHD");

                    b.HasIndex("MaHopDong")
                        .IsUnique();

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.HasIndex("MaQL");

                    b.ToTable("ChiTietHopDong");
                });

            modelBuilder.Entity("Common.Data.Model.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("Common.Data.Model.ChucVuNhanVien", b =>
                {
                    b.Property<int>("MaCVNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBoNhiem")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCVNV");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.ToTable("ChucVuNhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.CongTy", b =>
                {
                    b.Property<int>("MaCongTy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCongTy");

                    b.ToTable("CongTy");
                });

            modelBuilder.Entity("Common.Data.Model.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHopDong");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("Common.Data.Model.Luong", b =>
                {
                    b.Property<int>("MaLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaBacLuong")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuCap")
                        .HasColumnType("int");

                    b.Property<int>("MaThuong")
                        .HasColumnType("int");

                    b.Property<int>("luong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaLuong");

                    b.HasIndex("MaBacLuong");

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.HasIndex("MaPhuCap");

                    b.HasIndex("MaThuong");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("Common.Data.Model.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CongTyMaCongTy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("CongTyMaCongTy");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongBan");

                    b.HasIndex("MaCongTy");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("Common.Data.Model.PhuCap", b =>
                {
                    b.Property<int>("MaPhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoaiPhuCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucPhuCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaPhuCap");

                    b.ToTable("PhuCap");
                });

            modelBuilder.Entity("Common.Data.Model.QuanLy", b =>
                {
                    b.Property<int>("MaQL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CongTyMaCongTy")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCongTy")
                        .HasColumnType("int");

                    b.Property<double>("NamKinhNghiem")
                        .HasColumnType("float");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaQL");

                    b.HasIndex("CongTyMaCongTy");

                    b.ToTable("QuanLy");
                });

            modelBuilder.Entity("Common.Data.Model.QuyetDinhBoNhiem", b =>
                {
                    b.Property<int>("MaQDBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<int>("MaQL")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBoNhiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("MaQDBN");

                    b.HasIndex("MaChucVu")
                        .IsUnique();

                    b.HasIndex("MaNV");

                    b.HasIndex("MaQL");

                    b.ToTable("QuyetDinhBoNhiem");
                });

            modelBuilder.Entity("Common.Data.Model.Thuong", b =>
                {
                    b.Property<int>("MaThuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoaiThuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MucThuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaThuong");

                    b.ToTable("Thuong");
                });

            modelBuilder.Entity("Common.Data.Model.BangCap", b =>
                {
                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithMany("BangCaps")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.ChiTietHopDong", b =>
                {
                    b.HasOne("Common.Data.Model.HopDong", "HopDong")
                        .WithOne("ChiTietHopDong")
                        .HasForeignKey("Common.Data.Model.ChiTietHopDong", "MaHopDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithOne("ChiTietHopDong")
                        .HasForeignKey("Common.Data.Model.ChiTietHopDong", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Data.Model.QuanLy", "QuanLy")
                        .WithMany("ChiTietHopDongs")
                        .HasForeignKey("MaQL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");

                    b.Navigation("NhanVien");

                    b.Navigation("QuanLy");
                });

            modelBuilder.Entity("Common.Data.Model.ChucVuNhanVien", b =>
                {
                    b.HasOne("Common.Data.Model.ChucVu", "ChucVu")
                        .WithMany("ChucVuNhanVien")
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithOne("ChucVuNhanVien")
                        .HasForeignKey("Common.Data.Model.ChucVuNhanVien", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Common.Data.Model.Luong", b =>
                {
                    b.HasOne("Common.Data.Model.BacLuong", "BacLuong")
                        .WithMany("Luongs")
                        .HasForeignKey("MaBacLuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithOne("Luong")
                        .HasForeignKey("Common.Data.Model.Luong", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Data.Model.PhuCap", "PhuCap")
                        .WithMany("Luongs")
                        .HasForeignKey("MaPhuCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Data.Model.Thuong", "Thuong")
                        .WithMany("Luongs")
                        .HasForeignKey("MaThuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacLuong");

                    b.Navigation("NhanVien");

                    b.Navigation("PhuCap");

                    b.Navigation("Thuong");
                });

            modelBuilder.Entity("Common.Data.Model.NhanVien", b =>
                {
                    b.HasOne("Common.Data.Model.CongTy", "CongTy")
                        .WithMany("NhanViens")
                        .HasForeignKey("CongTyMaCongTy");

                    b.HasOne("Common.Data.Model.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongTy");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Common.Data.Model.PhongBan", b =>
                {
                    b.HasOne("Common.Data.Model.CongTy", "CongTy")
                        .WithMany("PhongBans")
                        .HasForeignKey("MaCongTy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongTy");
                });

            modelBuilder.Entity("Common.Data.Model.QuanLy", b =>
                {
                    b.HasOne("Common.Data.Model.CongTy", "CongTy")
                        .WithMany("QuanLies")
                        .HasForeignKey("CongTyMaCongTy");

                    b.Navigation("CongTy");
                });

            modelBuilder.Entity("Common.Data.Model.QuyetDinhBoNhiem", b =>
                {
                    b.HasOne("Common.Data.Model.ChucVu", "ChucVu")
                        .WithOne("QuyetDinhBoNhiem")
                        .HasForeignKey("Common.Data.Model.QuyetDinhBoNhiem", "MaChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Data.Model.NhanVien", "NhanVien")
                        .WithMany("QuyetDinhBoNhiems")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Data.Model.QuanLy", "QuanLy")
                        .WithMany("QuyetDinhBoNhiems")
                        .HasForeignKey("MaQL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("NhanVien");

                    b.Navigation("QuanLy");
                });

            modelBuilder.Entity("Common.Data.Model.BacLuong", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("Common.Data.Model.ChucVu", b =>
                {
                    b.Navigation("ChucVuNhanVien");

                    b.Navigation("QuyetDinhBoNhiem");
                });

            modelBuilder.Entity("Common.Data.Model.CongTy", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("PhongBans");

                    b.Navigation("QuanLies");
                });

            modelBuilder.Entity("Common.Data.Model.HopDong", b =>
                {
                    b.Navigation("ChiTietHopDong");
                });

            modelBuilder.Entity("Common.Data.Model.NhanVien", b =>
                {
                    b.Navigation("BangCaps");

                    b.Navigation("ChiTietHopDong");

                    b.Navigation("ChucVuNhanVien");

                    b.Navigation("Luong");

                    b.Navigation("QuyetDinhBoNhiems");
                });

            modelBuilder.Entity("Common.Data.Model.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("Common.Data.Model.PhuCap", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("Common.Data.Model.QuanLy", b =>
                {
                    b.Navigation("ChiTietHopDongs");

                    b.Navigation("QuyetDinhBoNhiems");
                });

            modelBuilder.Entity("Common.Data.Model.Thuong", b =>
                {
                    b.Navigation("Luongs");
                });
#pragma warning restore 612, 618
        }
    }
}
